### ISSUE TITLE
LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)

### ISSUE THREAD

**Issue by deepakm-webonise** [vinsol-spree-contrib/spree_events_tracker#7]
Getting the following error while installing the extension

> LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)

```
bundle exec rails g spree_admin_insights:install
/home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:98:in `load_adapter'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:28:in `adapter_class'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:56:in `connect'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/sequel-4.32.0/lib/sequel/core.rb:108:in `connect'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/bundler/gems/spree-admin-insights-f864b16c976b/lib/spree_admin_insights/engine.rb:26:in `block in <class:Engine>'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/webonise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /home/webonise/sample/deepakmahakale.github/spreecommercedemo/config/environment.rb:5:in `<top (required)>'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/webonise/.rvm/gems/ruby-2.3.1@nfhs/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by catalin88** [comment]
I get the same error for the branch 3-1-stable:

`/usr/local/rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)`

**Comment by dsawa** [comment]
@catalin88 @deepakm-webonise 

In my case it turned out that problem came from spree_admin_insights.

There is already PR that fixes this issue. If you are impatient like me and problem comes from admin insights then you can add this:

```
gem 'spree_admin_insights', github: 'vinsol-spree-contrib/spree-admin-insights', branch: '3-1-sqlite-fix'
```

to your Gemfile. And then update it later to branch 3-1-stable when 
https://github.com/vinsol-spree-contrib/spree-admin-insights/pull/29 will be reviewed and merged.
